/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
/**
 *
 * @author ASUS
 */
public class DataIbuForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataIbuForm
     */
    public DataIbuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SK_cb = new javax.swing.JComboBox<>();
        Delete_bt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        UK_txt = new javax.swing.JTextField();
        Save_bt = new javax.swing.JButton();
        TanggalLahir_dc = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        Update_bt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NamaIbu_txt = new javax.swing.JTextField();
        NIK_txt = new javax.swing.JTextField();
        UmurIbu_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alamat_ta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BackMenu_bt = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        RK_cb = new javax.swing.JComboBox<>();
        ANC_cb = new javax.swing.JComboBox<>();

        SK_cb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SK_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih---", "Normal", "Prematur", "Keguguran", "Cacat", " ", " ", " ", " " }));
        SK_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SK_cbActionPerformed(evt);
            }
        });

        Delete_bt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Delete_bt.setText("HAPUS");
        Delete_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("TANGGAL LAHIR");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("UMUR KEHAMILAN");

        UK_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UK_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UK_txtActionPerformed(evt);
            }
        });

        Save_bt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Save_bt.setText("SIMPAN");
        Save_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_btActionPerformed(evt);
            }
        });

        TanggalLahir_dc.setDateFormatString("yyyy-MM-dd");
        TanggalLahir_dc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("NIK ");

        Update_bt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Update_bt.setText("UPDATE");
        Update_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("UMUR IBU");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("RIWAYAT KESEHATAN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("ALAMAT");

        NamaIbu_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NamaIbu_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaIbu_txtActionPerformed(evt);
            }
        });

        NIK_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NIK_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIK_txtActionPerformed(evt);
            }
        });

        UmurIbu_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Alamat_ta.setColumns(20);
        Alamat_ta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Alamat_ta.setRows(5);
        jScrollPane1.setViewportView(Alamat_ta);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("NAMA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("FORMULIR DATA IBU");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BackMenu_bt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BackMenu_bt.setText("KEMBALI");
        BackMenu_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackMenu_btActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("RIWAYAT SKRINNING");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("STATUS KEHAMILAN");

        RK_cb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RK_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih---", "Tidak Anda", "Diabetes", "Gangguan darah", "Penyakit ginjal kronis", "Kegemukan", "Tekanan darah tinggi", "Penyakit Tiroid", "Lupus", "HIV/AIDS", "Depresi", " " }));
        RK_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RK_cbActionPerformed(evt);
            }
        });

        ANC_cb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANC_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih---", "Belum Skrinning", "Triwulan 1", "Triwulan 2", "Triwulan 3", " ", " ", " " }));
        ANC_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANC_cbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BackMenu_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(477, 477, 477)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(UmurIbu_txt)
                                        .addComponent(TanggalLahir_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NIK_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ANC_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UK_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SK_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NamaIbu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RK_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(Save_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Update_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Delete_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackMenu_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NamaIbu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NIK_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UmurIbu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TanggalLahir_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UK_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SK_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANC_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RK_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(297, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SK_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SK_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SK_cbActionPerformed

    public void setFields(String nama, String nik, String umur_ibu, java.util.Date tanggal_Lahir, String UK, String alamat, String status, String ANC, String RK) {
        NamaIbu_txt.setText(nama);
        NIK_txt.setText(nik);
        UmurIbu_txt.setText(umur_ibu);
        TanggalLahir_dc.setDate(tanggal_Lahir);
        UK_txt.setText(UK);
        Alamat_ta.setText(alamat);
        SK_cb.setSelectedItem(status);
        ANC_cb.setSelectedItem(ANC);
        RK_cb.setSelectedItem(RK);
    }
    
    private void Delete_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btActionPerformed
        NamaIbu_txt.setText("");
        NIK_txt.setText("");
        UmurIbu_txt.setText("");
        TanggalLahir_dc.setDate(null);
        UK_txt.setText("");
        Alamat_ta.setText("");
        SK_cb.setSelectedIndex(0);
        ANC_cb.setSelectedIndex(0);
        RK_cb.setSelectedIndex(0);
    }//GEN-LAST:event_Delete_btActionPerformed

    private void UK_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UK_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UK_txtActionPerformed

    private void Save_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_btActionPerformed
        // Mendapatkan nilai input dari komponen-komponen
        String nama = NamaIbu_txt.getText();
        String nik = NIK_txt.getText();
        String umur_ibu = UmurIbu_txt.getText();
        java.util.Date tanggal_Lahir = TanggalLahir_dc.getDate();
        String UK = UK_txt.getText();
        String alamat = Alamat_ta.getText();
        String status = (String) SK_cb.getSelectedItem();
        String ANC = (String) ANC_cb.getSelectedItem();
        String RK = (String) RK_cb.getSelectedItem();

        // Memeriksa apakah ada data yang kosong
        if (nama.isEmpty() || nik.isEmpty() || umur_ibu.isEmpty() || tanggal_Lahir == null ||
            UK.isEmpty() || alamat.isEmpty() || status.isEmpty() || ANC.isEmpty() || RK.isEmpty()) {
            // Menampilkan pesan error jika ada data yang kosong
            JOptionPane.showMessageDialog(this, "Error: Terdapat data yang kosong", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                // Kode untuk menyimpan data ke database
                // Menghubungkan ke database
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pbo_aplikasi_kesehatan", "root", "");
                // Membuat pernyataan SQL
                String sql = "INSERT INTO ibu (nama, nik, umur_ibu, tanggal_Lahir, UK, alamat, status, ANC, RK)" +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                // Membuat prepared statement
                PreparedStatement pstmt = conn.prepareStatement(sql);
                // Mengatur nilai parameter pada prepared statement
                pstmt.setString(1, nama);
                pstmt.setString(2, nik);
                pstmt.setString(3, umur_ibu);
                pstmt.setDate(4, new java.sql.Date(tanggal_Lahir.getTime()));
                pstmt.setString(5, UK);
                pstmt.setString(6, alamat);
                pstmt.setString(7, status);
                pstmt.setString(8, ANC);
                pstmt.setString(9, RK);
                // Menjalankan pernyataan SQL untuk menyimpan data
                pstmt.executeUpdate();
                // Menampilkan pesan sukses
                JOptionPane.showMessageDialog(this, "Data berhasil diinput", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                // Menutup koneksi ke database
                pstmt.close();
                conn.close();
                NamaIbu_txt.setText("");
                NIK_txt.setText("");
                UmurIbu_txt.setText("");
                TanggalLahir_dc.setDate(null);
                UK_txt.setText("");
                Alamat_ta.setText("");
                SK_cb.setSelectedIndex(0);
                ANC_cb.setSelectedIndex(0);
                RK_cb.setSelectedIndex(0);
            }catch(SQLException ex){
                // Menampilkan pesan error jika terjadi kesalahan dalam operasi database
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Save_btActionPerformed

    private void Update_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btActionPerformed
        String nama = NamaIbu_txt.getText();
        String nik = NIK_txt.getText();
        String umur_ibu = UmurIbu_txt.getText();
        java.util.Date tanggal_Lahir = TanggalLahir_dc.getDate();
        String UK = UK_txt.getText();
        String alamat = Alamat_ta.getText();
        String status = (String) SK_cb.getSelectedItem();
        String ANC = (String) ANC_cb.getSelectedItem();
        String RK = (String) RK_cb.getSelectedItem();

        // Memeriksa apakah ada data yang kosong
        if (nama.isEmpty() || nik.isEmpty() || umur_ibu.isEmpty() || tanggal_Lahir == null ||
            UK.isEmpty() || alamat.isEmpty() || status.isEmpty() || ANC.isEmpty() || RK.isEmpty()) {
            // Menampilkan pesan error jika ada data yang kosong
            JOptionPane.showMessageDialog(this, "Error: Terdapat data yang kosong", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                // Kode untuk mengupdate data ke database
                // Menghubungkan ke database
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pbo_aplikasi_kesehatan", "root", "");
                // Membuat pernyataan SQL
                String sql = "UPDATE ibu SET nama = ?, umur_ibu = ?, tanggal_Lahir = ?, UK = ?, alamat = ?, status = ?, ANC = ?, RK = ? WHERE nik = ?";
                // Membuat prepared statement
                PreparedStatement pstmt = conn.prepareStatement(sql);
                // Mengatur nilai parameter pada prepared statement
                pstmt.setString(1, nama);
                pstmt.setString(2, umur_ibu);
                pstmt.setDate(3, new java.sql.Date(tanggal_Lahir.getTime()));
                pstmt.setString(4, UK);
                pstmt.setString(5, alamat);
                pstmt.setString(6, status);
                pstmt.setString(7, ANC);
                pstmt.setString(8, RK);
                pstmt.setString(9, nik);
                // Menjalankan pernyataan SQL untuk mengupdate data
                int rowsUpdated = pstmt.executeUpdate();
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal mengupdate data", "Error", JOptionPane.ERROR_MESSAGE);
                }
                // Menutup koneksi ke database
                pstmt.close();
                conn.close();
                NamaIbu_txt.setText("");
                NIK_txt.setText("");
                UmurIbu_txt.setText("");
                TanggalLahir_dc.setDate(null);
                UK_txt.setText("");
                Alamat_ta.setText("");
                SK_cb.setSelectedIndex(0);
                ANC_cb.setSelectedIndex(0);
                RK_cb.setSelectedIndex(0);
            } catch (SQLException ex) {
                // Menampilkan pesan error jika terjadi kesalahan dalam operasi database
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Update_btActionPerformed

    private void NamaIbu_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaIbu_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaIbu_txtActionPerformed

    private void NIK_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIK_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIK_txtActionPerformed

    private void BackMenu_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackMenu_btActionPerformed
        OptionMenu optionMenu = new OptionMenu();
        optionMenu.setVisible(true);
        this.getDesktopPane().add(optionMenu);
        this.dispose();
    }//GEN-LAST:event_BackMenu_btActionPerformed

    private void RK_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RK_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RK_cbActionPerformed

    private void ANC_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANC_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ANC_cbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ANC_cb;
    private javax.swing.JTextArea Alamat_ta;
    private javax.swing.JButton BackMenu_bt;
    private javax.swing.JButton Delete_bt;
    private javax.swing.JTextField NIK_txt;
    private javax.swing.JTextField NamaIbu_txt;
    private javax.swing.JComboBox<String> RK_cb;
    private javax.swing.JComboBox<String> SK_cb;
    private javax.swing.JButton Save_bt;
    private com.toedter.calendar.JDateChooser TanggalLahir_dc;
    private javax.swing.JTextField UK_txt;
    private javax.swing.JTextField UmurIbu_txt;
    private javax.swing.JButton Update_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
