/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class OptionMenu extends javax.swing.JInternalFrame {
     
    /**
     * Creates new form OptionMenu
     */
    public OptionMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddDataAnak_bt = new javax.swing.JButton();
        AddDataIbu_bt = new javax.swing.JButton();
        ShowDataAnak_bt = new javax.swing.JButton();
        ShowDataIbu_bt = new javax.swing.JButton();

        setTitle("OPTION MENU");

        AddDataAnak_bt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddDataAnak_bt.setText("FORMULIR ANAK");
        AddDataAnak_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataAnak_btActionPerformed(evt);
            }
        });

        AddDataIbu_bt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddDataIbu_bt.setText("FORMULIR IBU");
        AddDataIbu_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataIbu_btActionPerformed(evt);
            }
        });

        ShowDataAnak_bt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ShowDataAnak_bt.setText("DAFTAR DATA ANAK");
        ShowDataAnak_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDataAnak_btActionPerformed(evt);
            }
        });

        ShowDataIbu_bt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ShowDataIbu_bt.setText("DAFTAR DATA IBU");
        ShowDataIbu_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDataIbu_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ShowDataAnak_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddDataAnak_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddDataIbu_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShowDataIbu_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(421, 421, 421))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddDataAnak_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddDataIbu_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ShowDataAnak_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShowDataIbu_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddDataAnak_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDataAnak_btActionPerformed
        DataAnakForm dataanakForm = new DataAnakForm();
        dataanakForm.setVisible(true);
        this.getDesktopPane().add(dataanakForm);
        this.dispose();
    }//GEN-LAST:event_AddDataAnak_btActionPerformed

    private void AddDataIbu_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDataIbu_btActionPerformed
        DataIbuForm dataibuForm = new DataIbuForm();
        dataibuForm.setVisible(true);
        this.getDesktopPane().add(dataibuForm);
        this.dispose();
    }//GEN-LAST:event_AddDataIbu_btActionPerformed

    private void ShowDataAnak_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDataAnak_btActionPerformed
        TableAnakForm dataForm = new TableAnakForm();
        dataForm.setVisible(true);
        this.getDesktopPane().add(dataForm);
        this.dispose();
    }//GEN-LAST:event_ShowDataAnak_btActionPerformed

    private void ShowDataIbu_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDataIbu_btActionPerformed
        TableIbuForm tableibuForm = new TableIbuForm();
        tableibuForm.setVisible(true);
        this.getDesktopPane().add(tableibuForm);
        this.dispose();
    }//GEN-LAST:event_ShowDataIbu_btActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDataAnak_bt;
    private javax.swing.JButton AddDataIbu_bt;
    private javax.swing.JButton ShowDataAnak_bt;
    private javax.swing.JButton ShowDataIbu_bt;
    // End of variables declaration//GEN-END:variables
}
